### ISSUE TITLE
Let API talk to Tasking Manager RDS 

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/galaxy-api#171]
From discussion here  https://github.com/hotosm/galaxy-api/issues/153#issuecomment-1054069415
- Galaxy API should be able to connect to Tasking Manager RDS. Challenge comes from the resources living in different VPCs. 

@eternaltyro is working on resolving the issue

cc @itskshitiz321 @JorgeMartinezG

**Comment by eternaltyro** [comment]
Components

- Security group rules for TM RDS (allowing connections from Galaxy API security group)
- Peering connection between the two VPCs (w/ Private DNS hostnames and private addresses enabled)

**Comment by eternaltyro** [comment]
Both of these are done from the infrastructure side. I am currently setting up the container to connect to the database with the right credentials (See comments in #140)

**Comment by eternaltyro** [comment]
The new API service has been deployed to docker containers on AWS ECS and has been made temporarily accessible on galaxy-api-lb.hotosm.org

To be production worthy, the following needs to happen

- [ ] The API endpoint needs to be tested to verify that data is being returned for queries targeting data from:
  - [ ] Tasking Manager Database
  - [ ] Insights Database
  - [ ] Underpass Database
- [ ] Point galaxy-api.hotosm.org to the container load-balancer and remove galaxy-api-lb.hotosm.org
- [ ] Wait for DNS propagation and remove osm-stats.hotosm.org
- [ ]  Update the website with the new endpoint

I am hoping to get some support from an AWS Solutions Architect regarding the AWS Cloudfront redirection issue that would let us have `galaxy.hotosm.org/api/...` but until that happens, let's work with galaxy-api.hotosm.org

**Comment by d-rita** [comment]
_With the galaxy-ui:_
-  ✅ I connected my local frontend app (galaxy-ui) to `https://galaxy-api.hotosm.org` and was able to make a request to the `https://galaxy-api.hotosm.org/mapathon/summary` endpoint. I got back the data.

_With the API docs:_
-  ✅ While using the docs themselves, i.e. `https://galaxy-api.hotosm.org/docs`, I was able to retrieve OSM ids from the `osm-users/ids` endpoint. 
- ⛔️ However, I am yet to test out the authenticated routes because I cannot seem to get a token yet. When I sign in to OSM with the url I get back from the `/login` endpoint, I get an error: `The requested redirect uri is malformed or doesn't match client redirect URI.`  I do need some help with this part before I can go further.  cc: @eternaltyro

**Comment by d-rita** [comment]
@eternaltyro, these are the steps I took: 
- Go to the [login endpoint](https://galaxy-api.hotosm.org/docs#/default/login_url_auth_login_get) via docs. 
- Copy the URL response returned by the endpoint, and enter it into a new tab. 
- Logged in via OSM. 
- Got an error: 
<img width="588" alt="error" src="https://user-images.githubusercontent.com/31903212/167458429-9836b9f2-3c82-44f1-809f-3890e953d108.png">

**Comment by eternaltyro** [comment]
The callback URL domain should match the actual domain from which OAuth requests are made. I fixed this in the current Docker setup.
