### ISSUE TITLE
Generate Absolute Download URL by reading from Request : Rawdata 

### ISSUE THREAD

**Issue by kshitijrajsharma** [hotosm/galaxy-api#190]
Currently Raw data endpoint gets hosting URL and port from config , which is not very friendly and good way to do this. Plan is to get hosting URL and port from request URL so that we can avoid unnecessary config block and Endpoint can generate absolute download URL in any environment

**Comment by ramyaragupathy** [comment]
@itskshitiz321 - can you please expand on hosting URL and port information? It is unclear if you are related to DB or the requesting client or something specific to API.

**Comment by itskshitiz321** [comment]
It is about generating Download URL for file download ! It is not related with any DB information , for eg : Let's say we have hosted API in galaxy.hotosm.org , now when user is accessing endpoint they will be redirected to galaxy.hotosm.org/rawdata/current-snapshot , now when delivering file to user API need to provide absolute URL to user , while getting request plan is to grab url and port from request iteself , in that way even when API is hosted on staging setup or different url or is in localsetup it will still work and bind the file back to user . Previously I was storing those host and port information in config.txt file , now plan is to grab them from request itself so that we will get rid of config block and API can adapt itself wrt hosting url and port for generating downloadable absolute URL for rawdata processed file !  @ramyaragupathy

**Comment by ramyaragupathy** [comment]
Thanks for explaining @itskshitiz321 - it is clear now 💯
