### ISSUE TITLE
Support Shapefile output Format in Galaxy API  : Rawdata

### ISSUE THREAD

**Issue by kshitijrajsharma** [hotosm/galaxy-api#199]
In export tool most of the people use Shapefile data type format, plan is to go one by one starting with Shapefile for now. This is targeted to redirect Shapefile output format to galaxy from export tool without any changes to frontend

**Comment by ramyaragupathy** [comment]
@itskshitiz321 - per chat w/ @robsavoye I understand you will start OGR python binding to provide SHP file output. Could you please confirm?

**Comment by itskshitiz321** [comment]
I have tested out popular OGR binding library  [Fiona](https://fiona.readthedocs.io/en/latest/manual.html), It is a clean Binding of OGR specifically focused on I/O operations of geospatial binaries for python developers ! So that we can do our manual steps as well with the help of it ! I have ogr2ogr  command line functionality already implemented in API here,https://github.com/hotosm/galaxy-api/blob/1b44451ec17be763f6157bc0f92171b63de00b6d/src/galaxy/app.py#L863
with Fiona, it enables us to use python binding of ogr as well , Here this function uses clean ogr binding with Fiona
https://github.com/hotosm/galaxy-api/blob/1b44451ec17be763f6157bc0f92171b63de00b6d/src/galaxy/app.py#L745
