### ISSUE TITLE
Implementing a Python module for the API

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/galaxy-api#7]
Following from the[ initial conversations](https://docs.google.com/document/d/1nCEpzZrv1yy3Ggun890TsC9GAnLpAF2qry0O1uaOy8g/edit) we had on OSM-Stats-API - we need to develop a Python module for the API, that's installable using a package manager like `pip`. This way we let anyone use the module to invoke the data using the package.

**Comment by robsavoye** [comment]
This should also include unit level test cases for each endpoint of the user stories. Having the API has a loaded module will allow other projects to use the API for their own needs, and different UIs,

**Comment by ramyaragupathy** [comment]
cc @JorgeMartinezG @omranlm

**Comment by ramyaragupathy** [comment]
@robsavoye - Can you please elaborate on the implementation and the objective?

**Comment by robsavoye** [comment]
The plan is our API should not be tightly coupled to the Galaxy UI, to enable others to create their own UI using the Galaxy backend. It's also entirely possible others might want to write their own python script to analyze the statistics and validation differently than us. It should be entirely possible to not even use a UI of any kind. Each endpoint in the API should also have a unit level test case for it to support CI, instead of requiring a human to click on things for manual testing. Support for generating charts from the data should also be part of the API, the UI can just load the image.

**Comment by robsavoye** [comment]
As this a longer term task, I'll add some new issues breaking this down into smaller, sprint-sized tasks.
